name: Checkstyle
on: 
  push:
    branches:
      - "*"        # Trigger on any branch in your repository
    paths:
      - '/*.java'  # Trigger only for changes in Java files

  pull_request:
    branches: ["master", "develop"]
    paths:
      - '/*.java'  # Monitor all Java files

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions: # Add permissions for check enforcement
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get changed files
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '/*.java'
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
          
      - name: Install Dependencies
        run: mvn install -DskipTests
        
      - name: Run Checkstyle on Changed Files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            mvn checkstyle:check -Dcheckstyle.includes=$file
          done

      - name: Block PR on Checkstyle Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Checkstyle checks failed. Please fix the code formatting issues.')